/**
 * Vendors the webfonts the platform ships.
 *
 * Every family here is licensed under the SIL Open Font License, which permits
 * self-hosting; `public/fonts/OFL.txt` records that and names each family.
 *
 * Self-hosted rather than loaded from a third-party CDN for three reasons: the
 * public profile's Content-Security-Policy allows no external origin at all, a
 * font request to another domain is a request a visitor did not consent to,
 * and a menu behind a QR code must still render when a CDN is unreachable.
 *
 * Google's CSS endpoint is used only as the *source of truth for subsetting* —
 * it returns one `@font-face` per unicode range, which is what keeps an Arabic
 * visitor from downloading Latin glyphs and the reverse. Those ranges are
 * preserved verbatim; only the `src` URL is rewritten to a local path.
 *
 * Run with: node scripts/fetch-fonts.mjs
 * The output is committed, so a build never depends on this script or on
 * network access.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

/** Families, and the weights each one actually needs. */
const FAMILIES = [
  { family: 'Cairo', weights: [400, 600, 700] },
  { family: 'Tajawal', weights: [400, 500, 700] },
  { family: 'Amiri', weights: [400, 700] },
  { family: 'El Messiri', weights: [400, 600, 700] },
  { family: 'Playfair Display', weights: [400, 600, 700] },
  { family: 'Inter', weights: [400, 500, 700] },
];

/** Ranges we never ship: nobody's menu needs Cyrillic or Vietnamese. */
const DROP_SUBSETS = new Set(['cyrillic', 'cyrillic-ext', 'vietnamese', 'greek', 'greek-ext']);

const OUT_DIR = path.join(process.cwd(), 'public', 'fonts');

function slug(name) {
  return name.toLowerCase().replace(/\s+/g, '-');
}

async function fetchCss(family, weights) {
  const spec = `${family.replace(/ /g, '+')}:wght@${weights.join(';')}`;
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`;
  const response = await fetch(url, { headers: { 'user-agent': UA } });
  if (!response.ok) throw new Error(`${family}: ${response.status}`);
  return response.text();
}

/** Splits the returned CSS into blocks, each preceded by its subset comment. */
function parseBlocks(css) {
  const blocks = [];
  const pattern = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let match;
  while ((match = pattern.exec(css)) !== null) {
    blocks.push({ subset: match[1], body: match[2] });
  }
  return blocks;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const out = [
    '/**',
    ' * Self-hosted webfaces. Generated by scripts/fetch-fonts.mjs — do not edit.',
    ' *',
    ' * Each face keeps the unicode-range it was subset with, so a browser',
    ' * downloads only the script it is about to draw, and `font-display: swap`',
    ' * means text is never invisible while a face loads.',
    ' */',
    '',
  ];

  for (const { family, weights } of FAMILIES) {
    const css = await fetchCss(family, weights);
    const blocks = parseBlocks(css);
    let kept = 0;

    for (const { subset, body } of blocks) {
      if (DROP_SUBSETS.has(subset)) continue;

      const weight = /font-weight:\s*(\d+)/.exec(body)?.[1] ?? '400';
      const remote = /url\((https:\/\/[^)]+\.woff2)\)/.exec(body)?.[1];
      if (!remote) continue;

      const file = `${slug(family)}-${weight}-${subset}.woff2`;
      const bytes = Buffer.from(await (await fetch(remote)).arrayBuffer());
      await writeFile(path.join(OUT_DIR, file), bytes);
      kept += 1;

      out.push(body.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(/fonts/${file})`).trim(), '');
    }

    console.log(`${family}: ${kept} faces`);
  }

  await writeFile(path.join(process.cwd(), 'src', 'design', 'fonts.css'), out.join('\n'));
  console.log('wrote src/design/fonts.css');
}

await main();
